# Globals ----------------------------------------------------------------- {{{1
#

variables:
  GIT_DEPTH: 1  # clone only the current commit
  GIT_STRATEGY: clone  # make a fresh `git clone` of the repo for every new CI job
  GIT_SUBMODULE_STRATEGY: normal  # init and check out submodules
  CENTOS_RELEASE: '7.5'
  DOCKER_REGISTRY: registry.gitlab.mero.colo.seagate.com
  M0_VG_NO_SYMLINKS: "true"
  WORKSPACE_NAME: "${CI_PROJECT_NAME}${CI_PIPELINE_ID}"
  WORKSPACE_DIR:  "/home/gitlab-runner/workspaces/${CI_PROJECT_NAME}${CI_PIPELINE_ID}"

stages:
  - build
  # - test
  # - cleanup

before_script:
  - date -u -Isec
  - git log -1 --pretty=fuller
  - printenv

after_script:
  - date -u -Isec


# Build ------------------------------------------------------------------- {{{1
#

build:
  stage: build
  tags: [ m0vg ]
  except: [ tags ]

  script:
    # can't be defined in the 'variables:' section because it supports only
    # sinle level of variable expansion, e.g. A=$VAR; B=$A won't work for B
    - export JOB_NAME="${WORKSPACE_NAME}-build"

    - sudo rm -rf ${WORKSPACE_DIR}
    - mkdir -p ${WORKSPACE_DIR}
    - cp -a ../${CI_PROJECT_NAME} ${WORKSPACE_DIR}
    - cd ${WORKSPACE_DIR}

    # get fresh Mero copy
    - git clone --recursive --depth 1 --shallow-submodules http://gitlab.mero.colo.seagate.com/mero/mero.git

    # make sure that build image is up to date
    - docker pull $DOCKER_REGISTRY/mero/mero:$CENTOS_RELEASE

    # build Mero
    - time docker run --rm --name ${JOB_NAME}
                      -v ~+:/data -w /data/mero
                  $DOCKER_REGISTRY/mero/mero:$CENTOS_RELEASE
                      bash -c "KERNEL=/lib/modules/\$(yum list installed kernel | tail -n1 | awk '{ print \$2 }').x86_64/build ;
                               USER=\$(id -un)
                               CONFIGURE_OPTS=--with-linux=\$KERNEL MAKE_OPTS='-j10' scripts/m0"

    # containers run commands as 'root' user, seize ownership back
    - sudo chown -R $(id -u):$(id -g) .

# vim: foldmethod=marker shiftwidth=2 tabstop=2 expandtab
