# Globals ----------------------------------------------------------------- {{{1
#

variables:
  GIT_DEPTH: 1  # clone only the current commit
  GIT_STRATEGY: clone  # make a fresh `git clone` of the repo for every new CI job
  GIT_SUBMODULE_STRATEGY: normal  # init and check out submodules
  CENTOS_RELEASE: '7.5'
  DOCKER_REGISTRY: registry.gitlab.mero.colo.seagate.com
  M0_VG_NO_SYMLINKS: "true"
  WORKSPACE_NAME: "${CI_PROJECT_NAME}${CI_PIPELINE_ID}"
  WORKSPACE_DIR:  "/home/gitlab-runner/workspaces/${CI_PROJECT_NAME}${CI_PIPELINE_ID}"

stages:
  - build
  - test
  # - cleanup

before_script:
  - date -u -Isec
  - git log -1 --pretty=fuller
  - printenv

after_script:
  - date -u -Isec


# Build ------------------------------------------------------------------- {{{1
#

build:
  stage: build
  tags: [ m0vg ]
  except: [ tags ]
  script:
    # can't be defined in the 'variables:' section because it supports only
    # single level of variable expansion, e.g. A=$VAR; B=$A won't work for B
    - export JOB_NAME="${WORKSPACE_NAME}-${CI_JOB_NAME}"

    - sudo rm -rf ${WORKSPACE_DIR}
    - mkdir -p ${WORKSPACE_DIR}
    - cp -a ../${CI_PROJECT_NAME} ${WORKSPACE_DIR}
    - cd ${WORKSPACE_DIR}

    # get fresh Mero copy
    - git clone --recursive --depth 1 --shallow-submodules http://gitlab.mero.colo.seagate.com/mero/mero.git

    # make sure that build image is up to date
    - docker pull $DOCKER_REGISTRY/mero/mero:$CENTOS_RELEASE

    - |
      cat >mero/_build-m0.sh <<'EOF'
      set -eu -o pipefail

      KERNEL=$(yum list installed kernel | tail -n1 | awk '{ print $2 }')

      ./autogen.sh
      ./configure --with-linux=/lib/modules/${KERNEL}.x86_64/build
      make -j10
      EOF

    # Build Mero.
    - time docker run --rm --name ${JOB_NAME}
                      -v ~+:/data -w /data/mero
                  $DOCKER_REGISTRY/mero/mero:$CENTOS_RELEASE
                      bash -x ./_build-m0.sh

    # Build hax's C extension.
    - time docker run --rm --name ${JOB_NAME}
                      -v ~+:/data -w /data/hare
                  $DOCKER_REGISTRY/mero/mero:$CENTOS_RELEASE
                      make -C hax

    # containers run commands as 'root' user, seize ownership back
    - sudo chown -R $(id -u):$(id -g) .

# test_cfgen:
#   stage: test
#   tags: [ m0vg ]
#   except: [ tags ]
#   script:
#     - XXX

# vim: foldmethod=marker shiftwidth=2 tabstop=2 expandtab
